FROM openjdk

MAINTAINER shekhar@seleniumExpress

WORKDIR /usr/app/

COPY target/SpringConsumptionRestAPI-0.0.1-SNAPSHOT.jar /usr/app/

EXPOSE 8080

CMD [ "java","-jar","SpringConsumptionRestAPI-0.0.1-SNAPSHOT.jar" ]